version: "3.3"

services:

  influxdb:
    image: influxdb:1.8.4
    environment:
      - INFLUXDB_DB=devops
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_INSTALL_PLUGINS=aceiot-svg-panel
    depends_on:
      - influxdb
  metrics-config:
    build: 
      context: ./metrics-config
      dockerfile: Dockerfile
    volumes:
      - ./metrics-config:/app
    ports:
      - 8080:8080
    restart: always
  metrics-service:
    build: ./metrics-service
    environment:
      - INFLUXDB=http://influxdb:8086/devops
      - METRICS_CONFIG=http://metrics-config:8080
      - CRON=*/1 * * * *
    depends_on:
      - influxdb
      - metrics-config
    restart: always