{
 "title": "Quality Data",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sprint",
    "label": "Sprint",
    "query": "select distinct(sprint) from jira_bug"
   },
   {
    "name": "phase",
    "label": "Bug phase",
    "query": "select distinct(phase) from jira_bug"
   }
  ]
 },
 "panels": [
  {
   "title": "General indicators (for all sprints and all bug phases)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Created bugs",
   "type": "bargauge",
   "description": "Bugs that were opened in the first sprint in which they appeared are considered.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_sprint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(issueName) from jira_bug group by sprint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Closed bugs",
   "type": "bargauge",
   "description": "Closed bugs (status = 'Done') are considered in the last sprint in which they appear.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_lastSprint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(issueName) from jira_bug WHERE statusCategory = 'Done' group by lastSprint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Root causes",
   "type": "piechart",
   "description": "Sprint of all bugs for all sprints of all phases",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_rootcause",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(issueName) FROM jira_bug GROUP BY squad",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time spent on bugs (Avg)",
   "type": "stat",
   "description": "Considered the average time worked for all bugs that are 'Done'",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(bugWorklogTime) FROM jira_bug where bugWorklogTime > 0 and statusCategory = 'Done'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rework history (for sprint)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "$sprint",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
     "repeat": "sprint",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Bug hours",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(bugWorklogTime) * 100 FROM jira_bug where bugWorklogTime > 0 and lastSprint =~ /^(${sprint})$/ group by lastSprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Logged hours",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(timespent) from jira_hour where sprint =~ /^(${sprint})$/ group by sprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Bug hours",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(bugWorklogTime) * 100 FROM jira_bug where bugWorklogTime > 0 and lastSprint =~ /^(${sprint})$/ group by lastSprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Logged hours",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(timespent) from jira_hour where sprint =~ /^(${sprint})$/ group by sprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Bug hours",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(bugWorklogTime) * 100 FROM jira_bug where bugWorklogTime > 0 and lastSprint =~ /^(${sprint})$/ group by lastSprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Logged hours",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(timespent) from jira_hour where sprint =~ /^(${sprint})$/ group by sprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Bug hours",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(bugWorklogTime) * 100 FROM jira_bug where bugWorklogTime > 0 and lastSprint =~ /^(${sprint})$/ group by lastSprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Logged hours",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(timespent) from jira_hour where sprint =~ /^(${sprint})$/ group by sprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Bug hours",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(bugWorklogTime) * 100 FROM jira_bug where bugWorklogTime > 0 and lastSprint =~ /^(${sprint})$/ group by lastSprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Logged hours",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select sum(timespent) from jira_hour where sprint =~ /^(${sprint})$/ group by sprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Time to resolve bugs (for bug phase and sprint)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time to resolve bugs (AVG)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_sprint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(deltaTimeToResolveBug) from jira_bug where deltaTimeToResolveBug > 0 and statusCategory = 'Done' and phase =~ /^(${phase:pipe})$/  AND sprint =~ /^(${sprint:pipe})$/ group by sprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Amount of bugs fixed, but not resolved",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_sprint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select count(issueName) from jira_bug where deltaTimeToResolveBug = 0 and statusCategory = 'Done' and phase =~ /^(${phase:pipe})$/  AND sprint =~ /^(${sprint:pipe})$/ group by sprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Worklog on bugs (for bug phase and sprint)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time spent on bugs (AVG)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_lastSprint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(bugWorklogTime) FROM jira_bug where bugWorklogTime > 0 and phase =~ /^(${phase})$/ and lastSprint =~ /^(${sprint})$/ group by lastSprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Time spent on bugs (SUM)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_lastSprint",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(bugWorklogTime) FROM jira_bug where bugWorklogTime > 0 and phase =~ /^(${phase})$/ and lastSprint =~ /^(${sprint})$/ group by lastSprint",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Bug phase (for sprint)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$sprint",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
     "repeat": "sprint",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_phase",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE sprint =~ /^(${sprint})$/ GROUP BY phase",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_phase",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE sprint =~ /^(${sprint})$/ GROUP BY phase",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_phase",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE sprint =~ /^(${sprint})$/ GROUP BY phase",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_phase",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE sprint =~ /^(${sprint})$/ GROUP BY phase",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_phase",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE sprint =~ /^(${sprint})$/ GROUP BY phase",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Sprint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "$sprint",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
     "repeat": "sprint",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_rootcause",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE sprint =~ /^(${sprint})$/ GROUP BY rootcause",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_rootcause",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE sprint =~ /^(${sprint})$/ GROUP BY rootcause",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_rootcause",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE sprint =~ /^(${sprint})$/ GROUP BY rootcause",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_rootcause",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE sprint =~ /^(${sprint})$/ GROUP BY rootcause",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$sprint",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_rootcause",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE sprint =~ /^(${sprint})$/ GROUP BY rootcause",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Bug status progress (for bug phase and sprint)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bug progress in: $phase",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
     "repeat": "phase",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_statusCategory",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(issueName) FROM jira_bug WHERE phase = '$phase' AND sprint =~ /^(${sprint:pipe})$/ GROUP BY statusCategory",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Dataset from this dashboard (for all sprints and all bug phases)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dataset",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT issueName, summary, issueType, category, phase, sprint, lastSprint,  resolutionDate, bugWorklogTime, deltaTimeToResolveBug, rootcause, status, statusCategory from jira_bug",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}