{
 "title": "Tech Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment Frequency (per week)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Deployments per week",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") as deploys FROM \"deploy\" WHERE $timeFilter GROUP BY time(1w, 3d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deployment Failure Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "deploy",
     "query": "SELECT 100 - (mean(\"success\") * 100) FROM \"deploy\" WHERE $timeFilter Group By time(1w, 3d)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lead Time for Changes (All time)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" },
    { "expression": "$D + $E", "type": "math" }
   ]
  },
  {
   "title": "Build Duration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"duration\") FROM \"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "worst",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(projectDuration) FROM (SELECT last(\"duration\") AS projectDuration  FROM \"build\" WHERE $timeFilter GROUP BY \"project\" )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Quality built-in", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "New Bugs in Production",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"duration\") FROM \"bug\" WHERE $timeFilter GROUP BY time(1w, 3d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Resolution Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "bug",
     "query": "SELECT mean(\"duration\") FROM \"bug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Test Pyramid",
   "type": "aceiot-svg-panel",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 9 },
   "targets": [
    {
     "alias": "Unit/Integration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(valuePerProject) FROM (SELECT LAST(\"value\") as valuePerProject FROM \"tests\" GROUP BY \"project\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Components",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(valuePerProject) FROM (SELECT LAST(\"value\") as valuePerProject FROM \"component_tests\" GROUP BY \"project\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "E2E",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(valuePerProject)  FROM (SELECT LAST(\"value\") as valuePerProject FROM \"e2e_tests\" GROUP BY \"project\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "coverage",
     "query": "SELECT mean(projectValue) FROM (SELECT last(value) as projectValue FROM \"coverage\"  group by project) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Code Metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Tech Debt (wd)",
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "code_smells",
     "query": "SELECT ceil(sum(projectValue) / 60 / 24) FROM (SELECT last(value) as projectValue FROM \"sqale_index\"  group by project)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total LOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lines",
     "query": "SELECT sum(projectValue) FROM (SELECT last(value) as projectValue FROM \"lines\"  group by project)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Code Complexity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "complexity",
     "query": "SELECT sum(projectValue) FROM (SELECT last(value) as projectValue FROM \"complexity\"  group by project)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cognitive Complexity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "complexity",
     "query": "SELECT sum(projectValue) FROM (SELECT last(value) as projectValue FROM \"cognitive_complexity\"  group by project)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Duplicated Blocks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "duplicated_blocks",
     "query": "SELECT sum(projectValue) FROM (SELECT last(value) as projectValue FROM \"duplicated_blocks\"  group by project)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Issues",
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "code_smells",
     "query": "SELECT sum(projectValue) FROM (SELECT last(value) as projectValue FROM \"code_smells\"  group by project)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "New Issues",
     "groupBy": [
      { "params": [ "project" ], "type": "tag" }
     ],
     "measurement": "code_smells",
     "query": "SELECT sum(projectValue) FROM (SELECT last(value) as projectValue FROM \"new_code_smells\"  group by project)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Security built-in", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Security",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SAST Vulnerabilities",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(projectValue) FROM (SELECT last(value) as projectValue FROM \"vulnerabilities\" group by project) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}